name: Deploy application manual to dev

on:
  workflow_dispatch:
env:
  TZ: Europe/Oslo

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build/test & push image
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/node-build-push-image-v2.yaml@chore/tob-6243-team-parameter
    secrets: inherit
    with:
      team: oppgjorsrapporter
      node-version: '24'
      image-tag: snapshot

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}
